=== jppreti/OrientacaoObjetos/java/src/main/resources/xml/documento17.dtd
<?xml version = "1.0" encoding="ISO-8859-1"?>

<!ELEMENT alunos (aluno+)>
<!ELEMENT aluno (nome,turma)>
<!ATTLIST aluno matricula ID #REQUIRED>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT turma (#PCDATA)>
<!ENTITY T1 "A1">
<!ENTITY T2 "B1">
<!ENTITY T3 "C1">
<!ATTLIST turma simbolo ENTITY #REQUIRED>

=== jppreti/OrientacaoObjetos/java/src/main/resources/xml/documento17.xml
<?xml version = "1.0" encoding="iso-8859-1"?>

<!DOCTYPE alunos SYSTEM "documento17.dtd">

<alunos>
    <aluno matricula = "m1">
        <nome> xxxxxxxxxxxxxxxx </nome>
        <turma simbolo = "&T1;"> 
            Terceiro semestre 
        </turma>
    </aluno>
    <aluno matricula = "m2">
        <nome> yyyyyyyyyyyyyyy </nome>
        <turma simbolo = "T2">
            Segundo semestre
        </turma>
    </aluno>
    <aluno matricula = "m3">
        <nome> wwwwwwwwww </nome>
        <turma simbolo = "T3">
            Terceiro semestre
        </turma>
    </aluno>
          
</alunos>
